### ISSUE TITLE
Информация про ракету Точка У.

### ISSUE THREAD

**Issue by SekaPe** [srghma/srghma.github.io#1]
Сейчас очень много говорят про ракету запущенную Украиной по Крематорску. 
Мало работал с гитхабом на данный момент, так что отсылаю вот так:

Русский:
Россия утверждает, что такие ракеты не использует, но еще 5 марта марта пусковые установки "Точка-У" были замечены в Беларуси, откуда они проследовали к границе с Украиной.

6 марта команда расследователей Conflict Intelligence [указывала](https://twitter.com/citeam_en/status/1500475853490343936?s=21), что ракета продолжает оставаться на вооружении в российской армии - несмотря на то, что большинство ракет заменены на более современные "Искандеры". 

В соцсетях также появлялись [видео](https://twitter.com/glediska/status/1512370032164098051) с пусковыми установками “Точки У”, помеченными белыми буквами V, - одним из тактических знаков, который используют части российской армии, участвующие во вторжении в Украину.

Международная правозащитная организация Amnesty International также предоставила [доказательства](https://www.amnesty.org/en/latest/news/2022/02/russian-military-commits-indiscriminate-attacks-during-the-invasion-of-ukraine/) того, что Россия применила тактические ракеты "Точка-У" 24 февраля во время удара по больнице в Угледаре (Донецкая область, территория под контролем Украины), в результате которого погибли четыре мирных жителя и 10 получили ранения.

English:
Russia claims, that they doesnt use this type of rockets, but lanchers "Tochka-U", was found on territory of Belarus in march of 5, where they start moving to border of Ukraine.

In march of 6, team of investigators Conflict Intelligence [said](https://twitter.com/citeam_en/status/1500475853490343936?s=21) that this type of rockets is still in equipment of russian army - despirt majority of rockets was changed to "Iskanders".

In social media started appearing [videos](https://twitter.com/glediska/status/1512370032164098051), with lauchers "Tochka-U" marked with white letters V - one of tactical marks, used by russian army, involved in invasion to Ukraine.

International human rights organization Amnesty International also provided [proofs](https://www.amnesty.org/en/latest/news/2022/02/russian-military-commits-indiscriminate-attacks-during-the-invasion-of-ukraine/) that Russia used "Tochka-U" in february of 24, during strike on hospital in Ugledar(Donetsk region, territory under Ukrainian control), as a result four civilians was killed, and 10 was injured.

**Comment by srghma** [comment]
https://youtu.be/e1e9fsMqI7Q?t=790

**Comment by srghma** [comment]
> наши по врагу не бьют если в городе

> кадыровцы начали хвастаться изнасилованными, фотки с девушками, бычков педофил
